# Generated by Django 3.0.4 on 2020-08-29 21:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_one', models.CharField(max_length=80)),
                ('option_two', models.CharField(max_length=80)),
                ('option_three', models.CharField(max_length=80)),
                ('option_four', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('point', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='questions.Option')),
                ('options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Option')),
                ('story_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Story')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
    ]
