# Generated by Django 3.0.4 on 2020-08-31 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.AddField(
            model_name='question',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='duration',
            field=models.FloatField(default=30),
        ),
        migrations.AddField(
            model_name='question',
            name='max_question',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='question',
            name='option_four',
            field=models.CharField(choices=[('A', 'Correct Answer'), ('W', 'Wrong Answer')], default='W', max_length=80),
        ),
        migrations.AddField(
            model_name='question',
            name='option_one',
            field=models.CharField(choices=[('A', 'Correct Answer'), ('W', 'Wrong Answer')], default='W', max_length=80),
        ),
        migrations.AddField(
            model_name='question',
            name='option_three',
            field=models.CharField(choices=[('A', 'Correct Answer'), ('W', 'Wrong Answer')], default='W', max_length=80),
        ),
        migrations.AddField(
            model_name='question',
            name='option_two',
            field=models.CharField(choices=[('A', 'Correct Answer'), ('W', 'Wrong Answer')], default='W', max_length=80),
        ),
        migrations.AddField(
            model_name='story',
            name='instruction',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.AddField(
            model_name='test',
            name='test_questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
    ]
