# Generated by Django 3.0.4 on 2020-08-31 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200831_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[(models.CharField(max_length=80), 'Option One'), (models.CharField(max_length=80), 'Option Two'), (models.CharField(max_length=80), 'Option Three'), (models.CharField(max_length=80), 'Option Four')], default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='option_four',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_one',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_three',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_two',
            field=models.CharField(max_length=80),
        ),
    ]
