# Generated by Django 3.0.4 on 2020-08-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20200831_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='option_four_is_answer',
            field=models.BooleanField(default=False, verbose_name='Is Option Four The Answer?'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_one_is_answer',
            field=models.BooleanField(default=False, verbose_name='Is Option One The Answer?'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_three_is_answer',
            field=models.BooleanField(default=False, verbose_name='Is Option Three The Answer?'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_two_is_answer',
            field=models.BooleanField(default=False, verbose_name='Is Option Two The Answer?'),
        ),
    ]
